env: "local" # dev, prod
storage_path: "./storage/trainers-manager.db"
postgre:
  user: postgres
  name: training
  port: 5432
  password: postgres
  host: localhost
  ssl: disable
server:
  port: 9045
  host: localhost
  read_timeout: 5
  write_timeout: 5
  prefork: false
  shutdown_timeout: 3

logging_handler:
  level: debug
  format: json
  discard: false
